---
- name: Log Received Insights Event Data
  hosts: localhost # Runs on the controller execution node
  connection: local # Use local connection within EE if needed
  gather_facts: no
  vars:
    # Default values if extra_vars are not passed correctly
    received_timestamp: "Not Provided"
    received_severity: "Not Provided"
    received_rule_id: "Not Provided"
    received_system_name: "Not Provided"
    full_event_payload: {} # Expecting a dictionary/JSON payload

  tasks:
    - name: Print Received Event Details
      ansible.builtin.debug:
        msg: |
          --- Insights Event Received by Controller Job ---
          Timestamp: {{ received_timestamp }}
          Severity: {{ received_severity }}
          Rule/CVE ID: {{ received_rule_id }}
          System Name: {{ received_system_name }}
          --- Full Payload Received ---
          {{ full_event_payload | to_nice_json }}
          --- End Event ---
