---
- name: Monitor Insights Critical Events via EDA Event Stream
  hosts: localhost
  gather_facts: false
  sources:
    - name: Listen to the Insights Event Stream configured in EDA UI
      ansible.eda.event_stream:
        name: Insights Event Stream
  rules:
    - name: Process Critical Vulnerability Finding from Event Stream
      condition: > 
        event.payload.bundle == "rhel" and
        event.payload.application == "vulnerability" and
        event.payload.events is defined and
        event.payload.events and
        event.payload.events[0].metadata.severity is defined and
        event.payload.events[0].metadata.severity == "Critical"
      action:
        debug:
          msg: |
            EVENT STREAM received Critical Vulnerability Event:
            Stream Source Name: {{ ansible_eda.source.name }} 
            Timestamp: {{ event.payload.timestamp | default('N/A') }}
            System Display Name: {{ event.payload.context.system.display_name | default('N/A') }}
            CVE: {{ event.payload.events[0].payload.rule_id | default('N/A') }}
            Severity: {{ event.payload.events[0].metadata.severity | default('N/A') }}
            Full Payload: {{ event.payload }}

        # --- Action 2: Trigger Remediation Job (Example) ---
        # Uncomment and configure *after* verifying payload with debug
        # run_job_template:
        #   name: "Remediate Critical CVE"  # Job Template name in your Controller
        #   organization: "Your Org Name"   # Org name in your Controller
        #   job_args:
        #     limit: "{{ event.payload.context.system.display_name | default(omit) }}" 
        #     extra_vars:
        #       # ** ADJUST THESE BASED ON YOUR DEBUG OUTPUT **
        #       target_cve: "{{ event.payload.events[0].payload.rule_id | default(omit) }}"
        #       insights_context: "{{ event.payload.context | default(omit) }}"

    # --- Rule for Critical Advisor Events ---
    - name: Process Critical Advisor Finding from Event Stream
      condition: >
        event.payload.bundle == "rhel" and
        event.payload.application == "advisor" and
        event.payload.events is defined and
        event.payload.events and
        event.payload.events[0].metadata.severity is defined and
        event.payload.events[0].metadata.severity == "Critical"
      action:
        debug:
          msg: | 
            EVENT STREAM received Critical Advisor Event:
            Stream Source Name: {{ ansible_eda.source.name }}
            Timestamp: {{ event.payload.timestamp | default('N/A') }}
            System Display Name: {{ event.payload.context.system.display_name | default('N/A') }}
            Rule ID: {{ event.payload.events[0].payload.rule_id | default('N/A') }}
            Description: {{ event.payload.events[0].payload.description | default('N/A') }}
            Severity: {{ event.payload.events[0].metadata.severity | default('N/A') }}
            Full Payload: {{ event.payload }}
