---
- name: Process Pre-Filtered Critical Vulnerability Events from Insights
  hosts: localhost
  gather_facts: false

  sources:
    - name: Listen for Pre-Filtered Insights Webhook Notifications
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000
  
  rules:
    - name: Process Received Critical Vulnerability Finding
      condition: >
        event.payload.bundle == "rhel" and
        event.payload.events is defined and
        event.payload.events

      action:
        debug:
          msg: | 
            RECEIVED PRE-FILTERED CRITICAL VULNERABILITY EVENT:
            Timestamp: {{ event.payload.timestamp | default('N/A') }}
            System Display Name: {{ event.payload.context.system.display_name | default('N/A') }}
            CVE: {{ event.payload.events[0].payload.rule_id | default('N/A') }} # Assuming CVE ID is rule_id
            Severity: {{ event.payload.events[0].metadata.severity | default('N/A') }} # Should always be Critical now
            Full Payload: {{ event.payload }}

        # --- Action 2: Trigger Remediation Job ---
        # run_job_template:
        #   name: "Remediate Critical CVE"
        #   organization: "Your Org Name"
        #   job_args:
        #     limit: "{{ event.payload.context.system.display_name | default(omit) }}" # Target the specific host
        #     extra_vars:
        #       # Pass necessary info to your remediation playbook
        #       # ** ADJUST THESE BASED ON YOUR DEBUG OUTPUT **
        #       target_cve: "{{ event.payload.events[0].payload.rule_id | default(omit) }}"
        #       insights_context: "{{ event.payload.context | default(omit) }}"
        #       # Add other vars as needed by your JT
